# Generated by Django 2.2.6 on 2019-10-19 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 1, 2, 44, 94300, tzinfo=utc)),
        ),
    ]
