# Generated by Django 2.2.6 on 2019-10-19 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0003_auto_20191019_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(upload_to='clothes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 10, 28, 19, 297963, tzinfo=utc)),
        ),
    ]
